name: Ship js trigger
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          registry-url: "https://registry.npmjs.org"
      - run: git switch master
      - run: npm install
      - run: npm run release:trigger
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
