name: Ship js trigger
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci

      - run: npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
