name: test ship js
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-node@master
      - run: git switch master
      - run: git fetch --tags
      - run: git log v0.11.1..HEAD --pretty=format:%s
